# Generated by Django 3.2.6 on 2022-08-16 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='data',
            field=models.DateField(default=datetime.date(2022, 8, 16)),
        ),
    ]
